"""empty message

Revision ID: ae53985a6324
Revises: 57d254eb1ce1
Create Date: 2020-05-21 13:39:06.373595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae53985a6324'
down_revision = '57d254eb1ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'url')
    # ### end Alembic commands ###
